### ISSUE TITLE
Bad network link

### ISSUE THREAD

**Issue by WinstonZhou888** [zhengjie9510/google-map-downloader#1]
Hi Zhengjie,
It is an amazing work you did, and I try to use it but keep telling me "Bad network link", like the following:

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\winston.zhu\code\anaconda3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:/Users/winston.zhu/Documents/SeeingMachines/Map/Google-Map-Downloader-master/Google-Map-Downloader-master/downloader_1.1.py", line 193, in run
    self.datas[i]=self.download(url)
  File "C:/Users/winston.zhu/Documents/SeeingMachines/Map/Google-Map-Downloader-master/Google-Map-Downloader-master/downloader_1.1.py", line 187, in download
    raise Exception("Bad network link.")
Exception: Bad network link.
```
Is there anything I can do to solve this problem? By the way, I am in Australia and use "Google" as the source.

**Comment by zhengjie9510** [comment]
I'm sorry to reply late.
Maybe you can change the server from "Google China" to "Google" in the main function, and then try again.

**Comment by zhengjie9510** [comment]
I'm sorry to reply late.
Maybe you can change the HEADERS in the download function, and try again.

**Comment by yongjunhe11** [comment]
Great, I change the header to '**User-Agent':'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36 QIHU 360SE**' , and everything is fine. Thank you zhengjie, as another question mentioned, that would be perfect if we can download the specific date of data.  However, thanks anyway.

**Comment by jaxxtrend** [comment]
Have same issue. Changing user agent to actual(like my web browser) doesn't work for me.

**Comment by lauraset** [comment]
> Have same issue. Changing user agent to actual(like my web browser) doesn't work for me.

Me, too. Have you solved it?

**Comment by cytsese** [comment]
谷歌数据源也许是更新了，我通过抓包获取岛实际map的地址为 ‘https://khms3.google.com/kh/v=908?x=206773&y=130092&z=18’，这应该是导致网络连接失败的原因？

**Comment by lyf6** [comment]
@cytsese 你解决这个问题了吗而且khms0-khms3来回切换。不知道该怎么办了
