### ISSUE TITLE
可以下载多时间序列的历史影像吗？

### ISSUE THREAD

**Issue by huberLiu2020** [zhengjie9510/Google-Map-Downloader#12]
请问该程序如何下载谷歌的多时间序列的历史影像吗？非常感谢。

**Comment by zhengjie9510** [comment]
这个程序不可以哦

**Comment by Arandinglv** [comment]
你好, 多时间序列的历史影响需要通过Google earth pro软件上下载. https://github.com/alsrnv/google_earth_pro_downloader
