### ISSUE TITLE
bad network link

### ISSUE THREAD

**Issue by GuoXin-Ink** [zhengjie9510/Google-Map-Downloader#14]
"After multiple attempts to change the headers in the code, I am still encountering the 'bad network link' error. May I inquire if there are alternative solutions available? Your assistance would be greatly appreciated. Thank you for your time and consideration. Best wishes!"

**Comment by zzw1123** [comment]
Have you solved the 'bad network link'  problem?

**Comment by GuoXin-Ink** [comment]
Thank you for your concern. I have already resolved this issue.
Best regards!
